{{- if .Values.monitoring.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: grafana
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: {{ .Values.monitoring.grafana.image }}
        ports:
        - containerPort: {{ .Values.monitoring.grafana.port }}
          name: http
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "{{ .Values.monitoring.grafana.adminPassword }}"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: grafana
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - port: {{ .Values.monitoring.grafana.port }}
    targetPort: {{ .Values.monitoring.grafana.port }}
    nodePort: {{ .Values.monitoring.grafana.nodePort }}
    name: http
{{- end }}
