AWSTemplateFormatVersion: 2010-09-09

Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the keypair
  EnviromentName:
    Description: Select the environment
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
    ConstraintDescription: must be development or production

Mappings:
  MyRegionMap:
    us-east-2:
      HVM64: ami-013ce69c368262d19
    us-west-1:
      HVM64: ami-06f932bfd69e55cc3

  MyEnvironmentMap:
    dev:
      InstanceType: t2.micro
    prod:
      InstanceType: t2.small

Conditions:
  CreateEIPForProd: !Equals [ !Ref EnviromentName, prod ]

Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref AWS::Region
        - HVM64
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref EnviromentName
        - InstanceType
      KeyName: !Ref MyKeyName
  MyProdEIP:
    Type: AWS::EC2::EIP
    Condition: CreateEIPForProd
    Properties:
      InstanceId: !Ref MyVMInstance
