[control_plane]
jarvis ansible_host=10.0.0.148 ansible_user=reza node_ip=10.0.0.148 node_name=jarvis node_role=control-plane workload_label=monitoring

[workers]
thor ansible_host=10.0.0.149 ansible_user=reza node_ip=10.0.0.149 node_name=thor node_role=worker workload_label=apps

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_ed25519
timezone=America/Vancouver
lab_user=reza
lab_network=10.0.0.0/24
k3s_server_ip=10.0.0.148
k3s_server_port=6443
metallb_ip_range=10.0.0.200-10.0.0.220
longhorn_replica_count=2
longhorn_version=1.6.2
grafana_admin_password=password
prometheus_retention=15d
jenkins_admin_password=password
registry_ip=10.0.0.206
registry_port=5000
base_domain=rezaops.com
cp_ip=10.0.0.148
worker_ip=10.0.0.149
aws_region=us-east-1
aws_access_key_id=KEY
aws_secret_access_key=PASSWORD
internal_dns_records='[{"name":"grafana","ip":"10.0.0.148"},{"name":"prometheus","ip":"10.0.0.148"},{"name":"alertmanager","ip":"10.0.0.148"},{"name":"jaeger","ip":"10.0.0.148"},{"name":"jenkins","ip":"10.0.0.148"},{"name":"argocd","ip":"10.0.0.148"},{"name":"vault","ip":"10.0.0.148"},{"name":"longhorn","ip":"10.0.0.148"},{"name":"registry","ip":"10.0.0.148"},{"name":"portainer","ip":"10.0.0.149"},{"name":"api","ip":"10.0.0.149"}]'
# Pi-hole
pihole_ip=10.0.0.201
pihole_password=password
ingress_ip=10.0.0.200
