apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-microservice
  labels:
    app: notification-restapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-restapp
  template:
    metadata:
      labels:
        app: notification-restapp
    spec:
      containers:
      - name: notification-service
        image: stacksimplify/kube-notifications-microservice:3.0.0-AWS-XRay
        ports:
        - containerPort: 8096
        imagePullPolicy: Always
        env:
        - name: AWS_MAIL_SERVER_HOST
          value: "smtp-service"
        - name: AWS_MAIL_SERVER_USERNAME
          value: "AKIAVRUVVS7YPVRZXJ4V"
        - name: AWS_MAIL_SERVER_PASSWORD
          value: "BMbOe/sHR2IEZH16W4ZJD9YbK1nH2fb1a8PgZBCxYQWC"
        - name: AWS_MAIL_SERVER_FROM_ADDRESS
          value: "rezachegini0101@gmail.com "
