apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
---
{{- end }}
{{- if .Values.jenkins.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.jenkins.namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
{{- end }}
