apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: "{{ .Values.database.user }}"
  DB_PASSWORD: "{{ .Values.database.password }}"
  SECRET_KEY: "{{ .Values.database.secretKey }}"
